# Generated by Django 4.1.4 on 2023-01-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('descreption', models.TextField(max_length=500)),
            ],
        ),
    ]
