# Generated by Django 4.1.4 on 2023-01-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0002_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
