# Generated by Django 4.1.4 on 2023-01-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0004_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.TextField(default='hello'),
        ),
    ]
