# Generated by Django 4.1.4 on 2023-01-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0005_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='model',
            field=models.TextField(default='helloXX'),
        ),
    ]
