# Generated by Django 4.1.4 on 2023-01-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0007_alter_car_image_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.TextField(choices=[('123', '2013'), ('2014', '444444'), ('2015', '2015'), ('2016', '2016')], default='hello'),
        ),
    ]
